### ISSUE TITLE
Solve the problems with installing the plugin on Bitbucket

### ISSUE THREAD

**Issue by kryptag** [Praqma/tracey-bitbucket-eiffel-rabbitmq-post-receive-hook#24]
Bitbucket's logs show us the error and says that its because of https://confluence.atlassian.com/bitbucketserverkb/bitbucket-server-fails-to-start-the-spring-webapplicationcontext-could-not-be-started-unresolved-constraint-in-bundle-779171541.html?utm_medium=logScan&utm_source=STP

**Comment by buep** [comment]
I'll write a conclusion on our findings now, but @kryptag please try to migrate us to a new bitbucket template - see #26

**Comment by buep** [comment]
## Conclusion - we can't make it work in it's current form

The version 0.9.0 version of the plugin was originally made by Andrey as thought the repository is called something with Bitbucket it is actually only Stash compliant.

The plugin works with Atlas-run, because that will start the Atlassian Stash version used a template for the Maven project, but we can't run the plugin on Bitbucket.

These are our problems:

* Installing the plugin on a Bitbucket Server 4.13.0 fails with an error that is explained to be about the server. The plugin install, but ends disabled. When enabling we find the error in the log, referencing this problem: https://confluence.atlassian.com/bitbucketserverkb/bitbucket-server-fails-to-start-the-spring-webapplicationcontext-could-not-be-started-unresolved-constraint-in-bundle-779171541.html?utm_medium=logScan&utm_source=STP
  * Our conclusion on that is the dependencies the plugin uses, are not available in Bitbucket. It is related to the spring ones.
* Trying a new Bitbucket server 5.4., we get the same error and the exact same behavior. We used a Bitbucket Docker hub image https://hub.docker.com/r/atlassian/bitbucket-server/ and evaluation license.
* Trying the old Stash server, version 3.11 from Docker hub https://hub.docker.com/r/atlassian/stash/ we hoped the dependencies would work so we could conclude our above hypothesis. But we get compatibility versions with Java as our plugin uses Java 8 and Stash works with Java 7 in those version. https://confluence.atlassian.com/bitbucketserverkb/installing-add-on-gets-stuck-and-throws-unsupported-major-minor-version-52-0-792308991.html?utm_medium=logScan&utm_source=STP

So our conclusion is that we don't want to spend time trying to fix the dependencies problem, but instead create a new template for Bitbucket hook-plugin using Atlas-SDK to generate it, so the dependencies should work from start of.
We don't have that much code, so it should be easy to move into the new project.

Then we are following latest and greatest version and can easier get support.
